import { getMovieIdFromUrl } from "../utils/helpers/getIDMovie.js";
import renderHeaderFooter from "../utils/helpers/renderHeader-Footer.js";
import renderMenuMobile from "../utils/helpers/renderMenuMobile.js";
import { setMenuMobile } from "../components/layout/mobile-menu.js";
// import { setFavorites } from "../components/movie/add-favorites.js";
import { getMovieIdController } from "../controllers/pages/movie.page.controller.js";
import { getTitleMoviesController } from "../controllers/pages/home.page.controller.js";
import { getTitleMoviesMobileController } from "../controllers/pages/home.page.controller.js";
import { setSelectTab } from "../components/common/tabs-page-movie.js";
import { initBtnTicket } from "../components/booking/ticket-button.js";
import { setScrollScreen } from "../components/layout/nav-scroll.js";

const idPage = getMovieIdFromUrl();
renderHeaderFooter();
renderMenuMobile();
setMenuMobile();
// setFavorites();
getMovieIdController(idPage);
getTitleMoviesController();
getTitleMoviesMobileController();
setSelectTab();
initBtnTicket(idPage);
setScrollScreen();