import { getMovieIdFromUrl } from "../utils/helpers/getIDMovie.js";
import renderHeaderFooter from "../utils/helpers/renderHeader-Footer.js"; 
import renderMenuMobile from "../utils/helpers/renderMenuMobile.js";
import { setMenuMobile } from "../components/layout/mobile-menu.js";
import { setFavorites } from "../components/movie/add-favorites.js";
import { initActorsSection } from "../components/movie/actor-card.js";
import { initMovieHero } from "../components/movie/movie-hero.js";
import { initMovieDescription } from "../components/movie/movie-description.js";
import { initMovieScore } from "../components/movie/movie-score.js";
import { initReview } from "../components/movie/review.js";
import { initSearch } from "../components/search/search.js";
import { initSearchMobile } from "../components/search/mobile-search.js";
import { setSelectTab } from "../components/common/tabs-page-movie.js";
import { initBtnTicket } from "../components/booking/ticket-button.js";
import { setScrollScreen } from "../components/layout/nav-scroll.js";

getMovieIdFromUrl();
renderHeaderFooter(); renderMenuMobile();
setMenuMobile();
setFavorites();
initActorsSection();
initMovieHero();
initMovieDescription();
initMovieScore();
initReview();
initSearch();
initSearchMobile();
setSelectTab();
initBtnTicket();
setScrollScreen();