import { getMovieIdFromUrl } from "../utils/helpers/getIDMovie.js";
import renderHeaderFooter from "../utils/helpers/renderHeader-Footer.js";
import renderMenuMobile from "../utils/helpers/renderMenuMobile.js";
import { setMenuMobile } from "../components/layout/mobile-menu.js";
// import { setFavorites } from "../components/movie/add-favorites.js";
// import { initActorsSection } from "../components/movie/actor-card.js";
import { getMovieIdController } from "../controllers/components/movie.controller.js";
// import { initMovieScore } from "../components/movie/movie-score.js";
// import { initReview } from "../components/movie/review.js";
import { getTitleMoviesController } from "../controllers/components/movie.controller.js";
import { getTitleMoviesMobileController } from "../controllers/components/movie.controller.js";
import { setSelectTab } from "../components/common/tabs-page-movie.js";
// import { initBtnTicket } from "../components/booking/ticket-button.js";
import { setScrollScreen } from "../components/layout/nav-scroll.js";

const idPage = getMovieIdFromUrl();
renderHeaderFooter();
renderMenuMobile();
setMenuMobile();
// setFavorites();
// initActorsSection();
getMovieIdController(idPage);
// initMovieScore();
// initReview();
getTitleMoviesController();
getTitleMoviesMobileController();
setSelectTab();
// initBtnTicket();
setScrollScreen();